<?php
# This file was automatically generated by the MediaWiki 1.39.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See docs/Configuration.md for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Wiki LOCIE";
$wgMetaNamespace = "Wiki_LOCIE";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/test/mediawiki";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://intranet-locie.local.univ-savoie.fr";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## Autorise restrictions dans CSS
$wgAllowSiteCSSOnRestrictedPages = true;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "https://www.univ-smb.fr/locie/wp-content/uploads/sites/72/2020/10/logo-locie.svg",
	'icon' => "https://www.univ-smb.fr/locie/wp-content/uploads/sites/72/2020/10/logo-locie.svg",
];

## UPO means: this is also a user preference option

$wgEnableEmail = false;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost:/run/mysqld/mysqld10.sock";
$wgDBname = "mediawiki2";
$wgDBuser = "mediawiki_user";
$wgDBpassword = "2pktq9Za#!87";

# MySQL specific settings
$wgDBprefix = "locie";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "fr";

# Time zone
$wgLocaltimezone = "Europe/Paris";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "c6ec18f668d335929ab7d4ab757d0945a156e79982a42157d164fc81942e0a94";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Isoler les sessions de la copie de test de celles de la production.
$wgCookiePrefix = "locie_mediawiki_test";
$wgCookiePath = "/test/mediawiki";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "df94bb6e15c5d394";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

# Permissions de base
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;

# Lecture anonyme MediaWiki autorisée pendant la préparation du contrôle GRR.
$wgGroupPermissions['*']['read'] = true;

# Ne jamais créer automatiquement de compte lecteur.
$wgGroupPermissions['*']['autocreateaccount'] = false;

# Tous les utilisateurs connectés peuvent lire mais pas éditer
$wgGroupPermissions['user']['edit'] = false;

# Groupe local pour les éditeurs
$wgGroupPermissions['editor']['edit'] = true;
$wgGroupPermissions['editor']['read'] = true;

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
# wfLoadSkin( 'MinervaNeue' );
# wfLoadSkin( 'MonoBook' );
# wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Math' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SecureLinkFixer' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
# wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );
# extension en plus
wfLoadExtension( 'LinkTarget' );
wfLoadExtension( 'CreatePageUw' );
wfLoadExtension( 'IframePage' );

wfLoadExtension( 'Parsoid', 'vendor/wikimedia/parsoid/extension.json' );

# vérouillage pages spéciale
wfLoadExtension( 'Lockdown' );
$wgSpecialPageLockdown['Specialpages'] = [ 'sysop' ];

# =========================
# Configuration LDAP conservée mais inactive
# =========================
# Étape 1 : authentification locale MediaWiki uniquement.
# Les extensions et leur configuration sont conservées pour le retour arrière.
# wfLoadExtension( 'PluggableAuth' );
# wfLoadExtension( 'LDAPProvider' );
# wfLoadExtension( 'LDAPAuthentication2' );
#wfLoadExtension( 'LDAPAuthorization' );

/*
,
    "authorization": {
      "rules": {
        "attributes": {
          "ou": [
            "polytech",
            "polytech-acy",
            "polytech-chy"
          ]
        }
      }
    }
*/


# Fichier JSON de configuration LDAP
$LDAPProviderDomainConfigs = "ldap.json";
$LDAPProviderDomainConfigProvider =
	"\\MediaWiki\\Extension\\LDAPProvider\\DomainConfigProvider\\LocalJSONFile::newInstance";

# Garder aussi le login local MediaWiki
$wgPluggableAuth_EnableLocalLogin = true;
$LDAPAuthentication2AllowLocalLogin = true;

# Normaliser les identifiants LDAP en minuscules
$LDAPAuthentication2UsernameNormalizer = 'strtolower';

# Bouton de connexion LDAP
$wgPluggableAuth_Config['Connexion USMB'] = [
	'plugin' => 'LDAPAuthentication2',
	'data' => [
		'domain' => 'USMB'
	]
];

# =========================
# Fin config LDAP
# =========================



# End of automatically generated settings.
# Add more configuration options below.

$wgFileExtensions = [ 'png', 'gif', 'jpg', 'jpeg', 'doc',
	'xls', 'pdf', 'ppt', 'tiff', 'bmp', 'docx', 'xlsx', 'xlsm',
	'pptx', 'ps', 'odt', 'ods', 'odp', 'odg'
];

$wgExternalLinkTarget = '_blank';
$wgLinkTargetParentClasses = [ 'grrLink' ];
$wgLinkTargetDefault = '_self';

$wgIframePageSrc = [
    'usmb' => 'https://www.univ-smb.fr/',
    'grr' => 'https://intranet-locie.local.univ-savoie.fr/',
    'grr2' => 'https://grr-epu.univ-savoie.fr/'
];
$wgIframePageAllowPath = true;

// Option visualEditor
// Afficher l’option VisualEditor dans Préférences > Fonctionnalités bêta
$wgVisualEditorEnableBetaFeature = true;

// (optionnel) Activer VE par défaut pour les utilisateurs connectés
$wgDefaultUserOptions['visualeditor-enable'] = 1;
$wgDefaultUserOptions['visualeditor-editor'] = 'visualeditor';

// (optionnel) empêcher la désactivation
// $wgHiddenPrefs[] = 'visualeditor-enable';

/*
# =========================
# Debug LDAP (à activer si besoin)
# =========================
$wgDebugLogGroups['PluggableAuth'] = '/tmp/mw-PluggableAuth.log';
$wgDebugLogGroups['LDAPAuthentication2'] = '/tmp/mw-LDAPAuthentication2.log';
$wgDebugLogGroups['LDAPProvider'] = '/tmp/mw-LDAPProvider.log';
$wgDebugLogGroups['LDAPAuthorization'] = '/tmp/mw-LDAPAuthorization.log';
*/

# =========================
# Passerelle d'acces GRR - copie de test
# =========================
# L'extension est chargee, mais reste volontairement inactive jusqu'a la
# copie directe du secret depuis l'administration du module GRR mediawiki_auth.
wfLoadExtension( 'GrrAccessGate' );
$wgGrrAccessGateEnabled = false;
$wgGrrAccessGateSecret = '';

# Le secret reel reste dans un fichier local non versionne et refuse par
# Apache. Ce fichier definit uniquement $wgGrrAccessGateSecret.
$grrAccessGateSecretFile = __DIR__ . '/LocalSettings.grr-secret.php';
if (is_readable($grrAccessGateSecretFile)) {
	require $grrAccessGateSecretFile;
}
$wgGrrAccessGateCookieName = 'GRRMediaWikiAccessTest';
$wgGrrAccessGateAudience = 'mediawiki-test';
$wgGrrAccessGateAuthorizeUrl =
	'/test/grr/personnalisation/modules/mediawiki_auth/authorize.php';
$wgGrrAccessGateRefreshUrl =
	'/test/grr/personnalisation/modules/mediawiki_auth/refresh.php';
$wgGrrAccessGateWikiPath = '/test/mediawiki/';
$wgGrrAccessGateClockSkew = 30;
$wgGrrAccessGateMaxTokenLifetime = 600;
$wgGrrAccessGateRefreshInterval = 60;

# Etape 5 : les URL generees par MediaWiki passent par les points d'entree
# controles. Les anciens rest.php, img_auth.php et le dossier images sont
# refuses par Apache via les fichiers .htaccess de la copie de test.
$wgRestPath = "$wgScriptPath/grr_rest.php";
$wgUploadPath = "$wgScriptPath/grr_img_auth.php";
$wgImgAuthPath = "$wgScriptPath/grr_img_auth.php";
# Apres copie du secret GRR ci-dessus, passer $wgGrrAccessGateEnabled a true.
# Ne jamais recopier ce secret dans la documentation ou les journaux.
# =========================
# Fin passerelle d'acces GRR
# =========================
